spring:
  port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

